# Generated by Django 5.2.6 on 2025-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_user_bio_user_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
